### ISSUE TITLE
Create home/back button for every page

### ISSUE THREAD

**Issue by mslomski** [evanlws12/423-Term-Project#82]
There must be an obvious home button or back button for every page that let's the user escape the page they are on.

**Comment by slins1** [comment]
Back button is already set. I'll add a home function/button and start adding it to pages.

**Comment by evanlws12** [comment]
Funny story about this.. so I found a bug where the "Assign another promotion" button went to assign item instead of promotion, when I remembered the guy saying something about wanting a clear home button on every page. So I quickly did a find and replace and added home buttons on each page before I realized that this was an issue assigned to you. So if you haven't worked on it yet then it's already done for you on my branch, and all you need to do is test them on each page. If you did already do it then I can revert my commit

**Comment by mslomski** [comment]
Finished.
